config/routes.rb
Rails.application.routes.draw do
  resources :heroku_news

end

app/models/heroku_new.rb
class HerokuNew < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/heroku_news_controller.rb
class HerokuNewsController < ApplicationController
  before_action :set_heroku_news, only: [:show, :edit, :update, :destroy]

  # GET /heroku_news
  # GET /heroku_news.json
  def index
    @heroku_news = HerokuNew.all
  end

  # GET /heroku_news/1
  # GET /heroku_news/1.json
  def show
  end

  # GET /heroku_news/new
  def new
    @heroku_news = HerokuNew.new
  end

  # GET /heroku_news/1/edit
  def edit
  end

  # POST /heroku_news
  # POST /heroku_news.json
  def create
    @heroku_news = HerokuNew.new(heroku_news_params)

    respond_to do |format|
      if @heroku_news.save
        format.html { redirect_to @heroku_news, notice: 'Heroku new was successfully created.' }
        format.json { render :show, status: :created, location: @heroku_news }
      else
        format.html { render :new }
        format.json { render json: @heroku_news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /heroku_news/1
  # PATCH/PUT /heroku_news/1.json
  def update
    respond_to do |format|
      if @heroku_news.update(heroku_news_params)
        format.html { redirect_to @heroku_news, notice: 'Heroku new was successfully updated.' }
        format.json { render :show, status: :ok, location: @heroku_news }
      else
        format.html { render :edit }
        format.json { render json: @heroku_news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /heroku_news/1
  # DELETE /heroku_news/1.json
  def destroy
    @heroku_news.destroy
    respond_to do |format|
      format.html { redirect_to heroku_news_url, notice: 'Heroku new was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_heroku_news
      @heroku_news = HerokuNew.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def heroku_news_params
      params.require(:heroku_news).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/heroku_news_helper.rb
module HerokuNewsHelper
end

app/views/heroku_news/_form.html.erb
<%= form_for(@heroku_news) do |f| %>
  <% if @heroku_news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@heroku_news.errors.count, "error") %> prohibited this heroku_news from being saved:</h2>

      <ul>
      <% @heroku_news.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_area :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/heroku_news/edit.html.erb
<h1>Editing Heroku News</h1>

<%= render 'form' %>

<%= link_to 'Show', @heroku_news %> |
<%= link_to 'Back', heroku_news_path %>

app/views/heroku_news/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Heroku News</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
      <br> nowa linijka 1
      <br> nowa linijka 2
      <br> nowa linijka 3


slider #<div class="span6 offset2">



    </tr>
  </thead>

  <tbody>
    <% @heroku_news.each do |heroku_news| %>
      <tr>
        <td><%= heroku_news.title %></td>
        <td><%= heroku_news.description %></td>
        <td><%= link_to 'Show', heroku_news %></td>
        <td><%= link_to 'Edit', edit_heroku_news_path(heroku_news) %></td>
        <td><%= link_to 'Destroy', heroku_news, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>

</table>

<br>

<%= link_to 'New Heroku new', new_heroku_news_path %>

app/views/heroku_news/new.html.erb
<h1>New Heroku News</h1>

<%= render 'form' %>

<%= link_to 'Back', heroku_news_path %>

app/views/heroku_news/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @heroku_news.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @heroku_news.description %>
</p>

<%= link_to 'Edit', edit_heroku_news_path(@heroku_news) %> |
<%= link_to 'Back', heroku_news_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HerokuTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<div id="wrap">

<body>

<%= yield %>

</body>

</div>

</html>